# Generated by AI

class_name TextureGenerator

# ─── PICKING ──────────────────────────────────────────────────────────────────

static func pick_wall(dominant: int, pool: Array, alt_chance: float) -> ImageTexture:
	return _pick(pool, dominant, alt_chance)

static func pick_floor(dominant: int, pool: Array, alt_chance: float) -> ImageTexture:
	return _pick(pool, dominant, alt_chance)

static func _pick(pool: Array, dominant: int, alt_chance: float) -> ImageTexture:
	if randf() < alt_chance:
		var alts = range(pool.size()).filter(func(i): return i != dominant)
		return pool[alts[randi() % alts.size()]]
	return pool[dominant]

# ─── WALL TEXTURES — red-brown family ─────────────────────────────────────────

static func wall_large_brick() -> ImageTexture:
	return _make_brick(64, 64,
		Color(0.48, 0.22, 0.15),
		Color(0.55, 0.27, 0.18),
		Color(0.70, 0.63, 0.58),
		3, 6, 3
	)

static func wall_small_brick() -> ImageTexture:
	return _make_brick(64, 64,
		Color(0.45, 0.20, 0.14),
		Color(0.52, 0.25, 0.17),
		Color(0.68, 0.61, 0.56),
		5, 8, 2
	)

static func wall_rough_stone() -> ImageTexture:
	var width = 64
	var height = 64
	var img = Image.create(width, height, false, Image.FORMAT_RGB8)

	var stone_a = Color(0.46, 0.21, 0.14)
	var stone_b = Color(0.54, 0.26, 0.18)
	var mortar  = Color(0.68, 0.61, 0.56)

	var cw = width / 2.0
	var ch = height / 2.0
	var mt = 4

	for y in range(height):
		for x in range(width):
			var lx = fmod(x, cw)
			var ly = fmod(y, ch)
			var block = int(x / cw) + int(y / ch) * 2

			if lx < mt or ly < mt:
				img.set_pixel(x, y, mortar)
			else:
				var base = stone_a if block % 2 == 0 else stone_b
				var noise = randf_range(-0.04, 0.04)

				if randf() < 0.012:
					img.set_pixel(x, y, Color(0.25, 0.12, 0.08))
				else:
					img.set_pixel(x, y, Color(
						clamp(base.r + noise, 0.0, 1.0),
						clamp(base.g + noise, 0.0, 1.0),
						clamp(base.b + noise, 0.0, 1.0)
					))

	return ImageTexture.create_from_image(img)

# ─── FLOOR TEXTURES — dark gray family ────────────────────────────────────────

static func floor_cobble() -> ImageTexture:
	return _make_cobble(64, 64,
		Color(0.32, 0.32, 0.32),
		Color(0.28, 0.28, 0.28),
		Color(0.22, 0.22, 0.22),
		3, 3, 3, 4
	)

static func floor_large_cobble() -> ImageTexture:
	return _make_cobble(64, 64,
		Color(0.34, 0.34, 0.33),
		Color(0.29, 0.29, 0.29),
		Color(0.20, 0.20, 0.20),
		2, 2, 4, 5
	)

static func floor_flagstone() -> ImageTexture:
	var width = 64
	var height = 64
	var img = Image.create(width, height, false, Image.FORMAT_RGB8)

	var tile_a = Color(0.33, 0.33, 0.32)
	var tile_b = Color(0.29, 0.29, 0.28)
	var grout  = Color(0.20, 0.20, 0.20)

	var cols = 3
	var rows = 4
	var cw = width / float(cols)
	var ch = height / float(rows)
	var gt = 2

	for y in range(height):
		for x in range(width):
			var lx = fmod(x, cw)
			var ly = fmod(y, ch)
			var block = int(x / cw) + int(y / ch) * cols

			if lx < gt or ly < gt:
				img.set_pixel(x, y, grout)
			else:
				var base = tile_a if block % 2 == 0 else tile_b
				var noise = randf_range(-0.03, 0.03)

				img.set_pixel(x, y, Color(
					clamp(base.r + noise, 0.0, 1.0),
					clamp(base.g + noise, 0.0, 1.0),
					clamp(base.b + noise, 0.0, 1.0)
				))

	return ImageTexture.create_from_image(img)

# ─── HELPERS ──────────────────────────────────────────────────────────────────

static func _make_brick(width: int, height: int,
		brick_a: Color, brick_b: Color, mortar: Color,
		rows: int, cols: int, mortar_px: int) -> ImageTexture:

	var img = Image.create(width, height, false, Image.FORMAT_RGB8)

	var rh = height / float(rows)
	var cw = width / float(cols)

	for y in range(height):
		var row = int(y / rh)
		var local_y = fmod(y, rh)
		var offset = (cw / 2.0) if row % 2 == 1 else 0.0

		for x in range(width):
			var sx = fmod(x + offset, width)
			var col = int(sx / cw)
			var local_x = fmod(sx, cw)

			if local_y < mortar_px or local_x < mortar_px:
				img.set_pixel(x, y, mortar)
			else:
				var base = brick_a if (row + col) % 2 == 0 else brick_b
				var noise = randf_range(-0.03, 0.03)

				img.set_pixel(x, y, Color(
					clamp(base.r + noise, 0.0, 1.0),
					clamp(base.g + noise, 0.0, 1.0),
					clamp(base.b + noise, 0.0, 1.0)
				))

	return ImageTexture.create_from_image(img)

static func _make_cobble(width: int, height: int,
		stone_a: Color, stone_b: Color, mortar: Color,
		cols: int, rows: int, mortar_px: int, corner_r: int) -> ImageTexture:

	var img = Image.create(width, height, false, Image.FORMAT_RGB8)

	var cw = width / float(cols)
	var ch = height / float(rows)

	for y in range(height):
		for x in range(width):
			var row = int(y / ch)
			var col = int(x / cw)

			var lx = fmod(x, cw)
			var ly = fmod(y, ch)

			if lx < mortar_px or ly < mortar_px:
				img.set_pixel(x, y, mortar)
				continue

			var cx = lx - mortar_px
			var cy = ly - mortar_px
			var sw = cw - mortar_px
			var sh = ch - mortar_px

			var in_corner = false

			if cx < corner_r and cy < corner_r:
				in_corner = Vector2(cx, cy).distance_to(Vector2(corner_r, corner_r)) > corner_r
			elif cx > sw - corner_r and cy < corner_r:
				in_corner = Vector2(cx, cy).distance_to(Vector2(sw - corner_r, corner_r)) > corner_r
			elif cx < corner_r and cy > sh - corner_r:
				in_corner = Vector2(cx, cy).distance_to(Vector2(corner_r, sh - corner_r)) > corner_r
			elif cx > sw - corner_r and cy > sh - corner_r:
				in_corner = Vector2(cx, cy).distance_to(Vector2(sw - corner_r, sh - corner_r)) > corner_r

			if in_corner:
				img.set_pixel(x, y, mortar)
				continue

			var base = stone_a if (row + col) % 2 == 0 else stone_b
			var noise = randf_range(-0.03, 0.03)

			img.set_pixel(x, y, Color(
				clamp(base.r + noise, 0.0, 1.0),
				clamp(base.g + noise, 0.0, 1.0),
				clamp(base.b + noise, 0.0, 1.0)
			))

	return ImageTexture.create_from_image(img)
